### ISSUE TITLE
Bad documentation on the README.md file

### ISSUE THREAD

**Issue by Subastkar** [festo/sails-hook-sequelize#2]
Working with the relations between models, find out  that the example that is given on the README file is not correct, it has `associate` as the key when it should be `associations`.

```javascript
module.exports = {
  attributes: { ... },
  associations: function() {
      //   Model.reletionType(Model, opts );
       User.hasOne(Profile);
    });
  },
  ...
};
```

**Comment by festo** [comment]
Sorry, you ate right. This issue has been fixed.
